x-defaults: &defaults
  env_file:
    - path: .env.example
      required: false
    - path: .env
      required: false

services:

  vlt-core-db:
    container_name: vlt-core-db
    build:
      context: dolt
      dockerfile: Dockerfile
      args:
        DB_SCHEMA: vlt_repo
        DB_USER: ${VLT_CORE_DB_USER:-admin}
        DB_PASSWORD: ${VLT_CORE_DB_PASSWORD:-admin}
    image: watisluv/vlt-core-db:1.0.0
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - dolt_data:/var/lib/dolt
    <<: *defaults
    environment:
      DOLT_DISABLE_UPGRADE_WARNING: "1"
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_ONETIME_PASSWORD: true
      MYSQL_INITDB_SKIP_TZINFO: true
    healthcheck:
      test: [ "CMD", "dolt", "sql", "-q", "select current_timestamp();" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      vlt:

volumes:
  dolt_data:

networks:
  vlt:
    external: true