x-defaults: &defaults
  env_file:
    - path: .env.example
      required: false
    - path: .env
      required: false

services:

  vlt-core-db:
    container_name: vlt-core-db
    build:
      context: db
      dockerfile: Dockerfile
      args:
        DB_SCHEMA: vlt_repo
    image: watisluv/vlt-core-db:1.0.0
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - vlt_db_data:/var/lib/postgresql/data
    <<: *defaults
    environment:
      VLT_CORE_DB_USER: ${VLT_CORE_DB_USER:-admin}
      POSTGRES_DB: vlt_repo
      POSTGRES_USER: ${VLT_CORE_DB_USER:-admin}
      POSTGRES_PASSWORD: ${VLT_CORE_DB_PASSWORD:-admin}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${VLT_CORE_DB_USER} -h localhost -p 5432 -d vlt_repo" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      vlt:

volumes:
  vlt_db_data:

networks:
  vlt:
    external: true